#!/bin/sh
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 RaykTo <raktodev@gmail.com>

. /lib/functions.sh

valid_ipv4() {
	local ip="$1" a b c d extra octet
	case "$ip" in ''|*[!0-9.]*) return 1 ;; esac
	IFS=. read -r a b c d extra <<EOF
$ip
EOF
	[ -n "$a" ] && [ -n "$b" ] && [ -n "$c" ] && [ -n "$d" ] && [ -z "$extra" ] || return 1
	for octet in "$a" "$b" "$c" "$d"; do
		case "$octet" in ''|*[!0-9]*) return 1 ;; esac
		[ "$octet" -le 255 ] || return 1
	done
}

valid_mac() {
	printf '%s\n' "$1" | grep -Eq '^[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){5}$'
}

add_priority_ip() {
	valid_ipv4 "$1" || return
	PRIORITY_IPS="${PRIORITY_IPS}${PRIORITY_IPS:+ }$1"
}

is_priority_ip() {
	case " $PRIORITY_IPS " in *" $1 "*) return 0 ;; *) return 1 ;; esac
}

emit_device() {
	local ip="$1" mac="$2" name="$3" id
	valid_ipv4 "$ip" && valid_mac "$mac" || return
	is_priority_ip "$ip" && return
	mac="$(printf '%s' "$mac" | tr 'A-F' 'a-f')"
	id="$(printf '%s' "$mac" | tr -d ':')"
	case "$name" in ''|'*') name="Dispositivo $ip" ;; esac
	name="$(printf '%s' "$name" | tr '\t\r\n' '   ')"
	printf '%s\t%s\t%s\t%s\n' "$id" "$mac" "$ip" "$name"
}

collect_reservation() {
	local section="$1" ip mac name
	config_get ip "$section" ip
	config_get mac "$section" mac
	config_get name "$section" name
	emit_device "$ip" "$mac" "$name"
}

PRIORITY_IPS=''
config_load bwlimit
config_list_foreach main exempt_ip add_priority_ip

{
	config_load dhcp
	config_foreach collect_reservation host
	if [ -r /tmp/dhcp.leases ]; then
		while read -r _expires mac ip name _client; do
			emit_device "$ip" "$mac" "$name"
		done < /tmp/dhcp.leases
	fi
} | awk -F '\t' '!seen_mac[$2] && !seen_ip[$3] { seen_mac[$2]=1; seen_ip[$3]=1; print }'
