#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

TABLE_FAMILY="inet"
TABLE_NAME="bwlimit"
CHAIN_NAME="forward"

load_cfg() {
	config_load bwlimit
	config_get enabled main enabled 0
	config_get lan_if main lan_if br-lan
	config_get subnet main subnet 192.168.1.0/24
	config_get down_kbytes main down_kbytes 1250
	config_get up_kbytes main up_kbytes 1250
	config_get_bool log_drop main log_drop 0
	config_get offload_disable main disable_flow_offloading 0
	config_list_foreach main exempt_ip add_exempt
}

EXEMPT_SET=""
add_exempt() {
	local ip="$1"
	[ -n "$ip" ] || return
	if [ -n "$EXEMPT_SET" ]; then
		EXEMPT_SET="$EXEMPT_SET, $ip"
	else
		EXEMPT_SET="$ip"
	fi
}

flush_rules() {
	nft delete table "$TABLE_FAMILY" "$TABLE_NAME" 2>/dev/null
}

apply_rules() {
	local drop_suffix="drop"
	[ "$log_drop" = "1" ] && drop_suffix="counter log prefix \"bwlimit-drop \" drop"

	nft add table "$TABLE_FAMILY" "$TABLE_NAME"
	nft "add chain $TABLE_FAMILY $TABLE_NAME $CHAIN_NAME { type filter hook forward priority -5; policy accept; }"

	if [ -n "$EXEMPT_SET" ]; then
		nft add rule "$TABLE_FAMILY" "$TABLE_NAME" "$CHAIN_NAME" iifname "$lan_if" ip saddr "{ $EXEMPT_SET }" accept
		nft add rule "$TABLE_FAMILY" "$TABLE_NAME" "$CHAIN_NAME" oifname "$lan_if" ip daddr "{ $EXEMPT_SET }" accept
	fi

	nft add rule "$TABLE_FAMILY" "$TABLE_NAME" "$CHAIN_NAME" iifname "$lan_if" ip saddr "$subnet" limit rate over "$up_kbytes" kbytes/second $drop_suffix
	nft add rule "$TABLE_FAMILY" "$TABLE_NAME" "$CHAIN_NAME" oifname "$lan_if" ip daddr "$subnet" limit rate over "$down_kbytes" kbytes/second $drop_suffix
}

toggle_offloading() {
	[ "$offload_disable" = "1" ] || return
	uci -q set firewall.@defaults[0].flow_offloading='0'
	uci -q set firewall.@defaults[0].flow_offloading_hw='0'
	uci -q commit firewall
	/etc/init.d/firewall restart >/dev/null 2>&1
}

start_service() {
	EXEMPT_SET=""
	load_cfg
	flush_rules
	[ "$enabled" = "1" ] || return 0
	toggle_offloading
	apply_rules
}

stop_service() {
	flush_rules
}

reload_service() {
	start_service
}

service_triggers() {
	procd_add_reload_trigger bwlimit
}
