#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 RaykTo <raktodev@gmail.com>

START=94
STOP=11
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/libexec/nano-monitor/accounting-daemon
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger bwlimit firewall
	procd_add_interface_trigger 'interface.*.up' 'provider' /etc/init.d/nano-accounting restart
}
